import { describe, expect, it } from "vitest";
import { InvoiceStatus, type Invoice, type UserSettings } from "@/types";
import { validateInvoiceFiscalScope } from "./invoiceFiscalScope";
const settings={taxId:"12/345",sellerTaxNumber:"12/345"} as UserSettings;
const make=(patch:Partial<Invoice>={}):Invoice=>({id:"1",number:null,clientId:"c",date:"2026-07-11",serviceDate:"2026-07-10",paymentTermsDays:14,positions:[{id:"p",description:"Leistung",quantity:1,unit:"Stk",price:100,taxCategory:"STANDARD",taxRate:19}],vatRate:19,isSmallBusiness:false,introText:"",footerText:"",status:InvoiceStatus.DRAFT,sellerCountry:"DE",customerCountry:"DE",customerType:"BUSINESS",serviceCountry:"DE",currency:"EUR",...patch});
describe("Rechnungsumfang",()=>{
 it("erlaubt 19 %, 7 % und Kleinunternehmer",()=>{expect(validateInvoiceFiscalScope(make(),settings)).toBeNull();expect(validateInvoiceFiscalScope(make({serviceDate:undefined,servicePeriodStart:"2026-07-01",servicePeriodEnd:"2026-07-10",positions:[{id:"p",description:"x",quantity:1,unit:"Stk",price:1,taxCategory:"REDUCED",taxRate:7}]}),settings)).toBeNull();expect(validateInvoiceFiscalScope(make({isSmallBusiness:true,positions:[{id:"p",description:"x",quantity:1,unit:"Stk",price:1,taxCategory:"SMALL_BUSINESS",taxRate:0}]}),settings)).toBeNull()});
 it.each([[{serviceDate:undefined},"SERVICE_DATE_REQUIRED"],[{servicePeriodStart:"2026-07-01",servicePeriodEnd:"2026-07-02"},"SERVICE_DATE_REQUIRED"],[{serviceDate:undefined,servicePeriodStart:"2026-07-01"},"SERVICE_DATE_REQUIRED"],[{serviceDate:undefined,servicePeriodStart:"2026-07-02",servicePeriodEnd:"2026-07-01"},"SERVICE_PERIOD_INVALID"],[{customerType:"PRIVATE"},"UNSUPPORTED_MARKET_SCOPE"],[{customerCountry:"AT"},"UNSUPPORTED_MARKET_SCOPE"],[{serviceCountry:"AT"},"UNSUPPORTED_MARKET_SCOPE"],[{currency:"USD"},"UNSUPPORTED_MARKET_SCOPE"]] as const)("blockiert %#",(patch,code)=>expect(validateInvoiceFiscalScope(make(patch),settings)).toBe(code));
 it.each(["REVERSE_CHARGE","EXEMPT","ZERO"] as const)("blockiert %s",category=>expect(validateInvoiceFiscalScope(make({positions:[{id:"p",description:"x",quantity:1,unit:"Stk",price:1,taxCategory:category,taxRate:0}]}),settings)).toBe("UNSUPPORTED_TAX_CASE"));
 it.each([["STANDARD",18],["REDUCED",6]] as const)("blockiert %s %s",(taxCategory,taxRate)=>expect(validateInvoiceFiscalScope(make({positions:[{id:"p",description:"x",quantity:1,unit:"Stk",price:1,taxCategory,taxRate}]}),settings)).toBe("UNSUPPORTED_TAX_CASE"));
});
