import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { buildCanonicalInvoice } from "../../server/einvoice/canonicalInvoice.js";
import { serializeCanonicalInvoiceToCii } from "../../server/einvoice/ciiSerializer.js";

const root=path.resolve(import.meta.dirname,"../..");const tmp=path.join(root,"tmp","pdfs","zugferd-validation");const output=path.join(root,"output","pdf");await rm(tmp,{recursive:true,force:true});await mkdir(tmp,{recursive:true});await mkdir(output,{recursive:true});
const source={doc:{number:"RE-2026-0001",date:"2026-07-11",currency:"EUR",buyerReference:"BUYER-REF-1",serviceDate:"2026-07-10",dueDate:"2026-07-25",positions:[{id:"1",description:"Beratungsleistung",quantity:1,unit:"Std",price:100,taxCategory:"STANDARD",taxRate:19}]},settings:{companyName:"Muster GmbH",address:"Musterstraße 1\n10115 Berlin",sellerStreet:"Musterstraße",sellerHouseNumber:"1",sellerPostalCode:"10115",sellerCity:"Berlin",sellerElectronicAddress:"rechnung@muster.example",sellerTaxNumber:"12/345/67890",sellerVatId:"DE123456789",iban:"DE02120300000000202051",bic:"BYLADEM1001",locale:"de-DE",currency:"EUR"},client:{companyName:"Kunde GmbH",address:"Kundenweg 2\n20095 Hamburg",street:"Kundenweg",houseNumber:"2",postalCode:"20095",city:"Hamburg",invoiceEmail:"rechnung@kunde.example"}};
const invoice=buildCanonicalInvoice(source);const pdf=path.join(tmp,"source-pdfa3.pdf");const xml=path.join(tmp,"factur-x.xml");const combined=path.join(output,"zugferd-en16931-reference.pdf");await rm(combined,{force:true});await writeFile(xml,serializeCanonicalInvoiceToCii(invoice).replace("urn:factur-x.eu:1p0:en16931","urn:cen.eu:en16931:2017"),"utf8");
const jar=path.join(root,".cache","mustang","Mustang-CLI-2.24.0.jar");const render=spawnSync("java",["-jar",jar,"--action","pdf","--source",xml,"--out",pdf,"--language","de"],{encoding:"utf8"});process.stdout.write(render.stdout??"");process.stderr.write(render.stderr??"");if(render.status!==0)process.exitCode=1;
const combine=spawnSync("java",["-jar",jar,"--action","combine","--source",pdf,"--source-xml",xml,"--out",combined,"--format","zf","--version","2","--profile","E","--no-additional-attachments"],{encoding:"utf8"});process.stdout.write(combine.stdout??"");process.stderr.write(combine.stderr??"");if(combine.status!==0)process.exitCode=1;
const validate=spawnSync("java",["-jar",jar,"--action","validate","--source",combined,"--no-notices","--disable-file-logging"],{encoding:"utf8"});process.stdout.write(validate.stdout??"");process.stderr.write(validate.stderr??"");if(validate.status!==0||!String(validate.stdout).includes('<summary status="valid"/>')){console.error(`ZUGFeRD/PDF-A-Validierung fehlgeschlagen: ${combined}`);process.exitCode=1;}else console.log(`ZUGFeRD-Referenz validiert: ${combined}`);
const extracted=path.join(tmp,"extracted-factur-x.xml");const extract=spawnSync("java",["-jar",jar,"--action","extract","--source",combined,"--out",extracted],{encoding:"utf8"});if(extract.status!==0)throw new Error("Eingebettetes XML konnte nicht extrahiert werden.");const originalXml=await readFile(xml,"utf8");const extractedXml=await readFile(extracted,"utf8");if(originalXml!==extractedXml)throw new Error("Eingebettetes XML weicht von der kanonischen Quelldatei ab.");console.log("Eingebettetes XML ist bytegenau identisch.");
