import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { buildCanonicalInvoice } from "../../server/einvoice/canonicalInvoice.js";
import { serializeCanonicalInvoiceToCii } from "../../server/einvoice/ciiSerializer.js";

const root=path.resolve(import.meta.dirname,"../..");const cache=path.join(root,".cache","kosit");const out=path.join(cache,"reports");await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
const invoice=buildCanonicalInvoice({doc:{number:"RE-2026-0001",date:"2026-07-11",currency:"EUR",buyerReference:"BUYER-REF-1",serviceDate:"2026-07-10",sellerCountry:"DE",customerCountry:"DE",customerType:"BUSINESS",serviceCountry:"DE",dueDate:"2026-07-25",positions:[{id:"1",description:"Beratungsleistung",quantity:1,unit:"Std",price:100,taxCategory:"STANDARD",taxRate:19}]},settings:{companyName:"Muster GmbH",address:"Musterstraße 1\n10115 Berlin",sellerCountry:"DE",sellerStreet:"Musterstraße",sellerHouseNumber:"1",sellerPostalCode:"10115",sellerCity:"Berlin",sellerElectronicAddress:"rechnung@muster.example",sellerElectronicAddressScheme:"EM",sellerTaxNumber:"12/345/67890",sellerVatId:"DE123456789",iban:"DE02120300000000202051",bic:"BYLADEM1001"},client:{companyName:"Kunde GmbH",address:"Kundenweg 2\n20095 Hamburg",street:"Kundenweg",houseNumber:"2",postalCode:"20095",city:"Hamburg",invoiceEmail:"rechnung@kunde.example"}});
const xmlPath=path.join(out,"invoice-cii.xml");const en16931Xml=serializeCanonicalInvoiceToCii(invoice).replace("urn:factur-x.eu:1p0:en16931","urn:cen.eu:en16931:2017");await writeFile(xmlPath,en16931Xml,"utf8");
const run=spawnSync("java",["-jar",path.join(cache,"validator-1.6.2-standalone.jar"),"-s",path.join(cache,"config","scenarios.xml"),"-r",path.join(cache,"config"),"-o",out,xmlPath],{encoding:"utf8"});if(run.error?.code==="ENOENT")throw new Error("Java ist nicht installiert oder nicht im PATH.");if(run.stdout)process.stdout.write(run.stdout);if(run.stderr)process.stderr.write(run.stderr);
const reportPath=path.join(out,"invoice-cii-report.xml");const report=await readFile(reportPath,"utf8");const acceptable=/<rep:assessment[^>]*>[\s\S]*?<rep:accept\b/.test(report)&&!/<rep:assessment[^>]*>[\s\S]*?<rep:reject\b/.test(report);if(!acceptable){console.error(`KoSIT-Validierung fehlgeschlagen. Bericht: ${reportPath}`);process.exitCode=1;}else console.log("KoSIT-Validierung erfolgreich (ACCEPTABLE).");
