import type { Invoice } from "../types";
import { InvoiceStatus } from "../types";

export function createEmptyInvoice(id: string, clientId = ""): Invoice {
  return {
    id,
    number: null,
    offerId: undefined,
    clientId,
    clientName: "",
    clientCompanyName: "",
    clientContactPerson: "",
    clientEmail: "",
    clientPhone: null,
    clientVatId: null,
    clientAddress: "",
    projectId: undefined,
    date: new Date().toISOString().slice(0, 10),
    paymentTermsDays: 14,
    dueDate: undefined,
    positions: [],
    vatRate: 0,
    isSmallBusiness: false,
    smallBusinessNote: null,
    introText: "",
    footerText: "",
    status: InvoiceStatus.DRAFT,
    paymentDate: undefined,
    paidAt: null,
    canceledAt: null,
    isOverdue: false,
    isLocked: false,
    finalizedAt: null,
    sentAt: null,
    lastSentAt: null,
    lastSentTo: null,
    sentCount: 0,
    sentVia: null,
  };
}

export function normalizeInvoice(invoice: Invoice): Invoice {
  return {
    ...invoice,
    number: invoice.number ?? null,
    clientId: invoice.clientId ?? "",
    clientName: invoice.clientName ?? "",
    clientCompanyName: invoice.clientCompanyName ?? "",
    clientContactPerson: invoice.clientContactPerson ?? "",
    clientEmail: invoice.clientEmail ?? "",
    clientPhone: invoice.clientPhone ?? null,
    clientVatId: invoice.clientVatId ?? null,
    clientAddress: invoice.clientAddress ?? "",
    date: invoice.date ?? new Date().toISOString().slice(0, 10),
    paymentTermsDays: Number(invoice.paymentTermsDays ?? 14),
    positions: invoice.positions ?? [],
    vatRate: Number(invoice.vatRate ?? 0),
    isSmallBusiness: invoice.isSmallBusiness ?? false,
    smallBusinessNote: invoice.smallBusinessNote ?? null,
    introText: invoice.introText ?? "",
    footerText: invoice.footerText ?? "",
    status: invoice.status ?? InvoiceStatus.DRAFT,
    isLocked: invoice.isLocked ?? false,
    finalizedAt: invoice.finalizedAt ?? null,
    paidAt: invoice.paidAt ?? null,
    canceledAt: invoice.canceledAt ?? null,
    isOverdue: invoice.isOverdue ?? false,
    sentAt: invoice.sentAt ?? null,
    lastSentAt: invoice.lastSentAt ?? null,
    lastSentTo: invoice.lastSentTo ?? null,
    sentCount: invoice.sentCount ?? 0,
    sentVia: invoice.sentVia ?? null,
  };
}
