import { useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { ArrowDown, ArrowUp, Plus, Search, Trash2, X } from "lucide-react";
import type { PositionGroup, PositionGroupInput, PositionTemplate } from "@/app/positions/positionCatalogService";
import { AppButton } from "@/ui/AppButton";
import { AppNumberInput } from "@/ui/AppNumberInput";
import { UNIT_OPTIONS } from "./positionFormModel";

type Item = PositionGroupInput["items"][number];
type Props = { group?: PositionGroup; duplicate?: boolean; initialTemplate?: PositionTemplate; templates: PositionTemplate[]; busy: boolean; onClose: () => void; onSave: (input: PositionGroupInput) => Promise<void> };

const fromTemplate = (template: PositionTemplate): Item => ({ positionTemplateId: template.id, title: template.name, description: template.description, quantity: template.default_quantity ?? 1, unit: template.unit, unitPrice: template.default_unit_price, taxCategory: template.tax_category, taxRate: template.tax_rate, optional: false });
const fromGroup = (group: PositionGroup): Item[] => group.position_group_items.map((item) => ({ positionTemplateId: item.position_template_id ?? null, title: item.title, description: item.description, quantity: item.quantity, unit: item.unit, unitPrice: item.unit_price, taxCategory: item.tax_category, taxRate: item.tax_rate, optional: item.optional }));

export function PackageEditorDialog({ group, duplicate, initialTemplate, templates, busy, onClose, onSave }: Props) {
  const initialItems = useMemo(() => group ? fromGroup(group) : initialTemplate ? [fromTemplate(initialTemplate)] : [], [group, initialTemplate]);
  const [name, setName] = useState(group ? `${group.name}${duplicate ? " Kopie" : ""}` : "");
  const [description, setDescription] = useState(group?.description ?? "");
  const [category, setCategory] = useState(group?.category ?? "");
  const [items, setItems] = useState<Item[]>(initialItems);
  const [query, setQuery] = useState("");
  const matches = templates.filter((template) => template.name.toLocaleLowerCase("de").includes(query.toLocaleLowerCase("de")) && !items.some((item) => item.positionTemplateId === template.id));
  const update = (index: number, patch: Partial<Item>) => setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  const move = (index: number, direction: -1 | 1) => setItems((current) => { const next = [...current]; const target = index + direction; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return next; });
  if (typeof document === "undefined") return null;
  return createPortal(<div className="app-visual-viewport fixed inset-x-0 z-[80] flex items-end justify-center bg-black/45 sm:items-center sm:p-4"><div className="app-card max-h-[96%] w-full max-w-3xl overflow-y-auto overscroll-contain rounded-b-none p-5 safe-bottom sm:max-h-[90%] sm:rounded-2xl" role="dialog" aria-modal="true" aria-labelledby="package-editor-title">
    <div className="flex items-center justify-between gap-3"><h2 id="package-editor-title" className="text-xl font-semibold">{group && !duplicate ? "Paket bearbeiten" : "Neues Paket"}</h2><button aria-label="Schließen" onClick={onClose}><X /></button></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-sm font-medium">Paketname *</span><input maxLength={200} value={name} onChange={(event) => setName(event.target.value)} placeholder="Terrasse pflastern" /></label><label><span className="mb-1 block text-sm">Kategorie</span><input maxLength={100} value={category} onChange={(event) => setCategory(event.target.value)} /></label><label className="sm:col-span-2"><span className="mb-1 block text-sm">Beschreibung</span><textarea rows={2} maxLength={2000} value={description} onChange={(event) => setDescription(event.target.value)} /></label></div>
    <section className="mt-6"><h3 className="font-medium">Produkte und Leistungen hinzufügen</h3><label className="relative mt-2 block"><Search className="pointer-events-none absolute left-3 top-3 text-[var(--app-muted)]" size={17} /><input className="pl-10" aria-label="Produkte und Leistungen suchen" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Produkt oder Leistung suchen" /></label>{query && <div className="mt-2 max-h-44 overflow-y-auto rounded-xl border border-[var(--app-border)]">{matches.length === 0 ? <p className="p-3 text-sm text-[var(--app-muted)]">Keine weiteren Produkte oder Leistungen gefunden.</p> : matches.map((template) => <button key={template.id} type="button" className="flex w-full items-center justify-between gap-3 border-b border-[var(--app-border)] p-3 text-left last:border-b-0" onClick={() => { setItems((current) => [...current, fromTemplate(template)]); setQuery(""); }}><span>{template.name}</span><Plus size={17} /></button>)}</div>}</section>
    <section className="mt-6"><h3 className="font-medium">Enthaltene Positionen</h3>{items.length === 0 ? <p className="mt-2 rounded-xl border border-dashed border-[var(--app-border)] p-4 text-sm text-[var(--app-muted)]">Füge mindestens eine Position hinzu.</p> : <div className="mt-3 space-y-3">{items.map((item, index) => <div key={`${item.positionTemplateId ?? item.title}-${index}`} className="rounded-xl border border-[var(--app-border)] p-4"><div className="flex items-start justify-between gap-3"><strong className="min-w-0 truncate">{item.title}</strong><div className="flex"><button aria-label="Nach oben" disabled={index === 0} className="p-2 disabled:opacity-30" onClick={() => move(index, -1)}><ArrowUp size={17} /></button><button aria-label="Nach unten" disabled={index === items.length - 1} className="p-2 disabled:opacity-30" onClick={() => move(index, 1)}><ArrowDown size={17} /></button><button aria-label="Entfernen" className="p-2 text-red-600" onClick={() => setItems((current) => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={17} /></button></div></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><label><span className="mb-1 block text-xs">Menge</span><AppNumberInput min={0.01} step="any" value={item.quantity} onValueChange={(quantity) => update(index, { quantity })} /></label><label><span className="mb-1 block text-xs">Einheit</span><select value={item.unit} onChange={(event) => update(index, { unit: event.target.value })}>{UNIT_OPTIONS.filter(([value]) => value !== "OTHER").map(([value, label]) => <option key={value} value={value}>{label}</option>)}{!UNIT_OPTIONS.some(([value]) => value === item.unit) && <option value={item.unit}>{item.unit}</option>}</select></label><label><span className="mb-1 block text-xs">Preis</span><AppNumberInput min={0} step="any" suffix="€" value={item.unitPrice} onEmpty={() => update(index, { unitPrice: null })} onValueChange={(unitPrice) => update(index, { unitPrice })} /></label></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={item.optional} onChange={(event) => update(index, { optional: event.target.checked })} /> Optionale Position</label></div>)}</div>}</section>
    <div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><AppButton variant="secondary" onClick={onClose}>Abbrechen</AppButton><AppButton disabled={busy || !name.trim() || items.length === 0} onClick={() => void onSave({ name: name.trim(), description: description.trim(), category: category.trim(), items })}>{busy ? "Speichert …" : "Paket speichern"}</AppButton></div>
  </div></div>, document.body);
}
