import { useEffect, useState } from "react";
import { Package, Plus, Trash2, Wrench } from "lucide-react";
import { createPositionGroup, createPositionTemplate, deletePositionGroup, deletePositionTemplate, loadPositionGroups, loadPositionTemplates, type PositionGroup, type PositionTemplate } from "@/app/positions/positionCatalogService";
import { AppButton } from "@/ui/AppButton";
import { AppNumberInput } from "@/ui/AppNumberInput";
import { useToast } from "@/ui/FeedbackProvider";

const initial: { kind: "PRODUCT" | "SERVICE" | "TEMPLATE"; name: string; description: string; category: string; unit: string; price: number | null; taxRate: number; productNumber: string; manufacturer: string } = { kind: "SERVICE", name: "", description: "", category: "", unit: "Std", price: null, taxRate: 19, productNumber: "", manufacturer: "" };
export function PositionCatalogPage() {
  const toast = useToast(); const [templates, setTemplates] = useState<PositionTemplate[]>([]); const [groups, setGroups] = useState<PositionGroup[]>([]); const [form, setForm] = useState(initial); const [groupName, setGroupName] = useState(""); const [groupSelection, setGroupSelection] = useState<string[]>([]); const [busy, setBusy] = useState(false);
  const reload = async () => { try { const [nextTemplates, nextGroups] = await Promise.all([loadPositionTemplates(), loadPositionGroups()]); setTemplates(nextTemplates); setGroups(nextGroups); } catch (error) { toast.error(error instanceof Error ? error.message : "Katalog konnte nicht geladen werden."); } };
  useEffect(() => { void reload(); }, []);
  const save = async () => { setBusy(true); try { await createPositionTemplate({ kind: form.kind, name: form.name, description: form.description, category: form.category, unit: form.unit, defaultQuantity: 1, defaultUnitPrice: form.price, taxCategory: form.taxRate === 7 ? "REDUCED" : "STANDARD", taxRate: form.taxRate, productNumber: form.productNumber, manufacturer: form.manufacturer }); setForm(initial); await reload(); toast.success("Katalogposition gespeichert."); } catch (error) { toast.error(error instanceof Error ? error.message : "Speichern fehlgeschlagen."); } finally { setBusy(false); } };
  const saveGroup = async () => { const selected = templates.filter((template) => groupSelection.includes(template.id)); if (!groupName.trim() || selected.length === 0) return; setBusy(true); try { await createPositionGroup({ name: groupName, items: selected.map((template) => ({ positionTemplateId: template.id, title: template.name, description: template.description, quantity: template.default_quantity ?? 1, unit: template.unit, unitPrice: template.default_unit_price, taxCategory: template.tax_category, taxRate: template.tax_rate, optional: false })) }); setGroupName(""); setGroupSelection([]); await reload(); toast.success("Positionsgruppe gespeichert."); } catch (error) { toast.error(error instanceof Error ? error.message : "Gruppe konnte nicht gespeichert werden."); } finally { setBusy(false); } };
  return <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6"><div><div className="app-eyebrow">Stammdaten</div><h1 className="mt-1 text-2xl font-semibold">Produkte, Leistungen und Positionsgruppen</h1><p className="mt-2 text-sm text-[var(--app-muted)]">Diese Daten erscheinen beim Tippen in Rechnungen und Angeboten und dienen als verlässliche Preisquelle für KI-Vorschläge.</p></div>
    <section className="app-card p-5"><h2 className="font-semibold">Neue Katalogposition</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value as typeof form.kind })}><option value="SERVICE">Leistung</option><option value="PRODUCT">Produkt</option><option value="TEMPLATE">Vorlage</option></select><input placeholder="Bezeichnung" maxLength={200} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/><input placeholder="Kategorie" maxLength={100} value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}/><input placeholder="Einheit" maxLength={30} value={form.unit} onChange={(event) => setForm({ ...form, unit: event.target.value })}/><textarea className="sm:col-span-2" placeholder="Beschreibung" maxLength={2000} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })}/><AppNumberInput placeholder="Standardpreis" min={0} step="any" value={form.price} onValueChange={(price) => setForm({ ...form, price })}/><select value={form.taxRate} onChange={(event) => setForm({ ...form, taxRate: Number(event.target.value) })}><option value={19}>19 %</option><option value={7}>7 %</option></select>{form.kind === "PRODUCT" && <><input placeholder="Produktnummer" value={form.productNumber} onChange={(event) => setForm({ ...form, productNumber: event.target.value })}/><input placeholder="Hersteller" value={form.manufacturer} onChange={(event) => setForm({ ...form, manufacturer: event.target.value })}/></>}</div><div className="mt-4"><AppButton disabled={busy || !form.name.trim() || !form.unit.trim()} onClick={() => void save()}><Plus size={16}/> Speichern</AppButton></div></section>
    <section className="app-card p-5"><h2 className="font-semibold">Katalog</h2><div className="mt-3 divide-y divide-[var(--app-border)]">{templates.length === 0 ? <p className="py-4 text-sm text-[var(--app-muted)]">Noch keine Produkte oder Leistungen gespeichert.</p> : templates.map((template) => <div key={template.id} className="flex items-center gap-3 py-3">{template.kind === "PRODUCT" ? <Package size={18}/> : <Wrench size={18}/>}<label className="flex min-w-0 flex-1 items-center gap-3"><input type="checkbox" checked={groupSelection.includes(template.id)} onChange={(event) => setGroupSelection((current) => event.target.checked ? [...current, template.id] : current.filter((id) => id !== template.id))}/><span><span className="block font-medium">{template.name}</span><span className="block text-xs text-[var(--app-muted)]">{template.unit} · {template.default_unit_price === null ? "kein Preis" : `${template.default_unit_price.toFixed(2)} €`} · {template.tax_rate} %</span></span></label><button aria-label={`${template.name} löschen`} className="text-red-600" onClick={() => void deletePositionTemplate(template.id).then(reload)}><Trash2 size={16}/></button></div>)}</div></section>
    <section className="app-card p-5"><h2 className="font-semibold">Positionsgruppe aus Auswahl speichern</h2><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input className="flex-1" placeholder="Gruppenname, z. B. Terrasse pflastern" value={groupName} onChange={(event) => setGroupName(event.target.value)}/><AppButton disabled={busy || !groupName.trim() || groupSelection.length === 0} onClick={() => void saveGroup()}>Gruppe speichern</AppButton></div><div className="mt-4 space-y-2">{groups.map((group) => <div key={group.id} className="flex items-center justify-between rounded-xl border border-[var(--app-border)] p-3"><span><span className="block font-medium">{group.name}</span><span className="text-xs text-[var(--app-muted)]">{group.position_group_items.length} Positionen</span></span><button aria-label={`${group.name} löschen`} className="text-red-600" onClick={() => void deletePositionGroup(group.id).then(reload)}><Trash2 size={16}/></button></div>)}</div></section>
  </div>;
}
